### ISSUE TITLE
NYTimes isn't actually italicized

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/nyc-planning-style-guide#14]
https://dcp-digital-style-guide.netlify.com/#abbreviations

**Comment by andycochran** [comment]
It's not supposed to be. The examples show how you should format the text. This is confusing, especially because the examples are part of the 2nd sentence. I'll reword it…

**Comment by andycochran** [comment]
This is further complicated by the fact that sometimes quotes or italics are used to indicate what the example text is. Need to standardize this…
