### ISSUE TITLE
Review data viz colors 

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/nyc-planning-style-guide#5]
A [lot of thought](https://medium.com/nyc-planning-digital/experimenting-with-planning-color-standards-15b591d2a90c) was put into the hues in the data viz color palette. However, the values and saturation could probably be improved to be more aesthetically-pleasing and brand-specific. 

It also might be helpful to have more that 4 variants of each hue — e.g. variants at multiple values and multiple saturations for each of those values. However, the more color options there are, the more difficult it becomes to prescribe which to use for what case. 

We should also prescribe how to use color at < 100% opacity, such as overlays on a map (and how that relates to legends).

**Comment by andycochran** [comment]
@kchanba You might be interested in this issue. In addition to the work mentioned above to use APA’s Land-Based Classification Standards, I put some more thought a while ago into making the saturation/luminosity more consistent across our various hues. 

In the current color palette, some light colors are lighter than others, darks darker than others, etc. They're still too programmatically generated. 

Here's a palette I was working on (can send you the PSD if you like): 

![dcp-color-palette](https://user-images.githubusercontent.com/409279/66417724-a0186980-e9ce-11e9-89ae-ba5ac452166a.png)

**Comment by kchanba** [comment]
Would love to help and work on the palette in psd

**Comment by andycochran** [comment]
This was improved upon and implemented. Closing. Kinda related to #24.
